@startuml
'https://plantuml.com/class-diagram

package Market
{
class MarketSystem

package Market.Basket
{
class BasketManager
}
package Market.Clients
{
class ClientManager
}

MarketSystem -down-> BasketManager 
MarketSystem -down-> ClientManager
}

@enduml
